services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: bookit-papercut
    ports:
    - '8081:80'
    - '25:25'

volumes:
  postgres_data: